# Generated by Django 4.2.14 on 2024-08-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_menuitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='avarate_rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='offer',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
