# Generated by Django 4.2.14 on 2024-08-28 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_menuitem_avarate_rating_menuitem_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='offer',
            new_name='discount',
        ),
    ]
