# Generated by Django 4.2.14 on 2024-08-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_alter_review_menu_item_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='count_reviewer',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='rating_sum',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
