# Generated by Django 4.2.14 on 2024-08-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_menuitem_count_reviewer_menuitem_rating_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
