# Generated by Django 4.2.14 on 2024-08-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_favourite_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
