# Generated by Django 4.2.14 on 2024-10-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Success', 'Success'), ('Cancle', 'Cancle'), ('Failed', 'Failed')], default='Success', max_length=20),
        ),
    ]
