# Generated by Django 4.2.14 on 2024-10-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('Cash On Delivary', 'Cash On Delivary'), ('Online Payment', 'Online Payment')], default='Cash On Delivary', max_length=20),
        ),
    ]
